### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by vinnitu** [hvtuananh/lingpipe#1]
I'm trying to train model with model file size about 25MB

here I have error, but I don't know how to fix it

https://github.com/hvtuananh/lingpipe/blob/master/src/com/aliasi/spell/CompiledSpellChecker.java#L1319

```
     [java] Reading model from file=SpellCheck.model
     [java] Exception in thread "main" java.lang.StackOverflowError
     [java]     at java.util.DualPivotQuicksort.sort(DualPivotQuicksort.java:1506)
     [java]     at java.util.Arrays.sort(Arrays.java:264)
     [java]     at com.aliasi.spell.CompiledSpellChecker.completeTrieNode(CompiledSpellChecker.java:1314)
     [java]     at com.aliasi.spell.CompiledSpellChecker.completeTrieNode(CompiledSpellChecker.java:1319)
     [java]     at com.aliasi.spell.CompiledSpellChecker.completeTrieNode(CompiledSpellChecker.java:1319)
```

Help me fix it?
Maybe I need something to do with train data before training?

**Comment by RishiPrakash** [comment]
Don't use Arrays.sort; implement your own merge sort, it will solve the problem.
